In [ ]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# team

> Fetch team stats for individual games.

In [ ]:
#| default_exp team

In [ ]:
#| hide
from nbdev.showdoc import *
import pandas as pd
from typing import Optional
import requests

In [ ]:
#| export
def fetch_team_stats(team_id: str, date: Optional[str] = None):
    """
    Fetches all team stats for a particular team or if a date is passed then just for a particular game
    """
    if date:
        print(f"Fetching team stats for team_id:{team_id} on date:{date}...")
    else:
        print(f"Fetching all team stats for team_id:{team_id}...") 
    try:
        if date:
            team_url = f"https://github.com/seanyboi/rugbydata/blob/main/data/team/{team_id}/{date}.parquet?raw=true"
            team_stats = pd.read_parquet(team_url, engine="pyarrow")
            return team_stats
        else:
            team_url = f"https://github.com/seanyboi/rugbydata/blob/main/data/team/{team_id}"
            path = requests.get(team_url)
            urls = [f"https://github.com/seanyboi/rugbydata/blob/main/{p['path']}?raw=true" for p in path.json()["payload"]["tree"]["items"]]
            team_stats = pd.concat((pd.read_parquet(u, engine="pyarrow") for u in urls))
            return team_stats
    except Exception as e:
        print(f"No team stats for {team_id} because the team id does not exist. Please raise an issue! - {e}")

In [ ]:
fetch_team_stats(team_id="25901")

Fetching all team stats for team_id:25901...

,team,game_date,team_id,team_vs,team_vs_id,clean_breaks,conversion_goals,defenders_beaten,kick_percent_success,kicks,...,scrums_total,scrums_won,tackles,territory,total_free_kicks_conceded,total_lineouts,tries,turnover_knock_on,turnovers_conceded,yellow_cards
0,Harlequins,20230101,25901,Northampton Saints,25907,5.0,2.0,20.0,1.00,0.0,...,5.0,4.0,211.0,0.33,1.0,12.0,2.0,13.0,18.0,1.0
0,Harlequins,20230108,25901,Sale Sharks,25908,3.0,0.0,24.0,0.50,0.0,...,7.0,5.0,125.0,0.41,0.0,11.0,2.0,8.0,17.0,0.0
0,Harlequins,20230217,25901,Gloucester Rugby,25900,3.0,3.0,21.0,0.75,0.0,...,4.0,4.0,100.0,0.53,0.0,22.0,4.0,9.0,13.0,1.0
0,Harlequins,20230304,25901,Exeter Chiefs,116227,9.0,5.0,20.0,0.83,0.0,...,10.0,8.0,211.0,0.43,0.0,14.0,6.0,6.0,8.0,1.0
0,Harlequins,20230312,25901,Bristol Rugby,25899,7.0,3.0,33.0,0.75,0.0,...,12.0,11.0,104.0,0.48,1.0,7.0,4.0,9.0,12.0,1.0
0,Harlequins,20230325,25901,Saracens,25909,3.0,2.0,26.0,0.50,0.0,...,7.0,6.0,104.0,0.53,2.0,7.0,4.0,18.0,17.0,2.0
0,Harlequins,20230415,25901,Newcastle Falcons,25906,12.0,4.0,29.0,0.50,0.0,...,9.0,7.0,83.0,0.61,0.0,16.0,8.0,9.0,9.0,1.0
0,Harlequins,20230422,25901,Bath Rugby,25898,12.0,5.0,32.0,1.00,0.0,...,5.0,5.0,92.0,0.54,1.0,12.0,5.0,15.0,11.0,2.0
0,Harlequins,20230506,25901,Leicester Tigers,25903,5.0,1.0,21.0,1.00,0.0,...,6.0,6.0,114.0,0.52,0.0,16.0,2.0,17.0,15.0,1.0

In [ ]:
fetch_team_stats(team_id="25901", date="20230108")

Fetching team stats for team_id:25901 on date:20230108...

,team,game_date,team_id,team_vs,team_vs_id,clean_breaks,conversion_goals,defenders_beaten,kick_percent_success,kicks,...,scrums_total,scrums_won,tackles,territory,total_free_kicks_conceded,total_lineouts,tries,turnover_knock_on,turnovers_conceded,yellow_cards
0,Harlequins,20230108,25901,Sale Sharks,25908,3.0,0.0,24.0,0.5,0.0,...,7.0,5.0,125.0,0.41,0.0,11.0,2.0,8.0,17.0,0.0

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()